// Top-level guide pages, shown above the component list in the sidebar and
// the global docs search.
export const docsGettingStarted = [
  { label: "Installation", href: "/docs/installation" },
]

// Published component docs. Extend as pages are written under
// app/docs/components/<slug>/page.tsx. Shared by the sidebar and the
// global docs search.
export const docsComponents = [
  { label: "Alert", href: "/docs/components/alert" },
  { label: "Attachment", href: "/docs/components/attachment" },
  { label: "Avatar", href: "/docs/components/avatar" },
  { label: "Badge", href: "/docs/components/badge" },
  { label: "Breadcrumb", href: "/docs/components/breadcrumb" },
  { label: "Button", href: "/docs/components/button" },
  { label: "Button Group", href: "/docs/components/button-group" },
  { label: "Calendar", href: "/docs/components/calendar" },
  { label: "Card", href: "/docs/components/card" },
  { label: "Chart", href: "/docs/components/chart" },
  { label: "Checkbox", href: "/docs/components/checkbox" },
  { label: "Color Picker", href: "/docs/components/color-picker" },
  { label: "Color Swatch", href: "/docs/components/color-swatch" },
  { label: "Combobox", href: "/docs/components/combobox" },
  { label: "Command", href: "/docs/components/command" },
  { label: "Dialog", href: "/docs/components/dialog" },
  { label: "Drawer", href: "/docs/components/drawer" },
  { label: "Dropdown Menu", href: "/docs/components/dropdown-menu" },
  { label: "Empty", href: "/docs/components/empty" },
  { label: "Field", href: "/docs/components/field" },
  { label: "File Upload", href: "/docs/components/file-upload" },
  { label: "Header", href: "/docs/components/header" },
  { label: "Input", href: "/docs/components/input" },
  { label: "Input Group", href: "/docs/components/input-group" },
  { label: "Input OTP", href: "/docs/components/input-otp" },
  { label: "Item", href: "/docs/components/item" },
  { label: "Kanban", href: "/docs/components/kanban" },
  { label: "Kbd", href: "/docs/components/kbd" },
  { label: "Message", href: "/docs/components/message" },
  { label: "Message Scroller", href: "/docs/components/message-scroller" },
  { label: "Mobile Shell", href: "/docs/components/mobile-shell" },
  { label: "Notification", href: "/docs/components/notification" },
  { label: "Popover", href: "/docs/components/popover" },
  { label: "Progress", href: "/docs/components/progress" },
  { label: "Radio Group", href: "/docs/components/radio-group" },
  { label: "Rating", href: "/docs/components/rating" },
  { label: "Select", href: "/docs/components/select" },
  { label: "Separator", href: "/docs/components/separator" },
  { label: "Sidebar", href: "/docs/components/sidebar" },
  { label: "Slider", href: "/docs/components/slider" },
  { label: "Spinner", href: "/docs/components/spinner" },
  { label: "Sub Header", href: "/docs/components/sub-header" },
  { label: "Switch", href: "/docs/components/switch" },
  { label: "Table", href: "/docs/components/table" },
  { label: "Tabs", href: "/docs/components/tabs" },
  { label: "Tag", href: "/docs/components/tag" },
  { label: "Textarea", href: "/docs/components/textarea" },
  { label: "Timeline", href: "/docs/components/timeline" },
  { label: "Toast", href: "/docs/components/toast" },
  { label: "Tooltip", href: "/docs/components/tooltip" },
]
